---
- name: Include variables for RedHat family
  include_vars: "{{ ansible_distribution }}.yml"

- name: Set repo_bareos_os_ver
  set_fact:
    repo_bareos_os_ver: "{{ ansible_distribution_major_version }}"

- name: Set variable repo_bareos_release
  set_fact:
    repo_bareos_release: "{{ _repo_bareos_release }}/{{ repo_bareos_version }}"
  when: repo_bareos_release is not defined

- name: Include tasks for Debian family
  import_tasks: repo_debian.yml
  when: ansible_distribution == "Debian"

- name: Include tasks for RHEL family
  import_tasks: repo_redhat.yml
  when: ansible_os_family == "RedHat"
