---
- name: Include variables for RedHat family
  include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Set variables repo_bareos_os_ver
  set_fact:
    repo_bareos_os_ver: "{{ ansible_distribution_major_version }}"

- name: Set variable repo_bareos_release
  set_fact:
    repo_bareos_release: "{{ __repo_bareos_release }}/{{ repo_bareos_version }}"
  when: repo_bareos_release is not defined

- name: Include tasks for {{ ansible_os_family }} family
  include_tasks: repo_{{ ansible_os_family | lower }}.yml
