---
- name: Include tasks for Debian family
  import_tasks: repo_debian.yml
  when: ansible_distribution == "Debian" 

- name: Include tasks for RHEL family
  import_tasks: repo_centos.yml
  when: ansible_distribution == "CentOS" 
