---
# This is for installing missing python-apt lib's
- name: apt-get update  
  apt:
    update_cache: True

- name: Add apt key for bareos repository
  apt_key: 
    url: http://download.bareos.org/bareos/release/{{ repo_bareos_version }}/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.0/Release.key
    state: present

- name: Add official bareos repo (from bareos.org)
  apt_repository:
    repo: deb http://download.bareos.org/bareos/release/{{ repo_bareos_version }}/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.0 /
    filename: bareos
    state: present
