---
- name: Add official bareos repo (from bareos.org)
  yum_repository:
    name: bareos_bareos-{{ bareos_repo_version }}
    description: bareos:bareos-{{ bareos_repo_version }} ({{ ansible_distribution }}_{{ ansible_distribution_major_version }})
    baseurl: http://download.bareos.org/bareos/release/{{ bareos_repo_version }}/{{ repo_bareos_ansible_distribution }}_{{ ansible_distribution_major_version }}/
    enabled: "{{ bareos_repo_enabled }}"
    gpgkey: http://download.bareos.org/bareos/release/{{ bareos_repo_version }}/{{ repo_bareos_ansible_distribution }}_{{ ansible_distribution_major_version }}/repodata/repomod.xml.key
    gpgcheck: "{{ bareos_repo_gpgcheck }}"
    file: bareos
    state: present
