---
# This is for installing missing python-apt lib's
- name: apt-get update
  apt:
    update_cache: true
  become: true

- name: Add apt key for bareos repository
  apt_key:
    url: "http://download.bareos.org/bareos/{{ repo_bareos_release }}/\
      {{ ansible_distribution }}_{{ repo_bareos_os_ver }}.0/Release.key"
    state: present
  become: true

- name: Add official bareos repo (from bareos.org)
  apt_repository:
    repo: "deb http://download.bareos.org/bareos/{{ repo_bareos_release }}/\
      {{ ansible_distribution }}_{{ repo_bareos_os_ver }}.0  /"
    filename: "{{ repo_bareos_filename }}"
    mode: "0644"
    state: present
  become: true
