---
- name: Add official bareos repo (from bareos.org)
  yum_repository:
    name: bareos_bareos-{{ repo_bareos_release.split("/")[1] }}
    description: bareos-{{ repo_bareos_release.split("/")[1] }} ({{ ansible_distribution }}_{{ repo_bareos_os_ver }})
    baseurl:
      - http://download.bareos.org/bareos/{{ repo_bareos_release }}/{{ repo_bareos_distro }}_{{ repo_bareos_os_ver }}/
    enabled: "{{ repo_bareos_enabled }}"
    gpgkey: http://download.bareos.org/bareos/{{ repo_bareos_release }}/{{ repo_bareos_distro }}_{{ repo_bareos_os_ver }}/repodata/repomd.xml.key
    gpgcheck: "{{ repo_bareos_gpgcheck }}"
    file: "{{ repo_bareos_filename }}"
    state: present
  become: true
